### PR TITLE
fix: non-hacker confirm button disable conditions

### LINKED ISSUE #371: [PMS] Non-Hacker Check In Fixes
Following from #368, we need to fix the disable condition for `confirmButton` to match its corresponding condition for showing `ParticipantActionPopover`. Additionally, we can simply the `confirm_attendance_non_hacker` function to use `update_one` instead of `raw_update_one`.

### PR DESCRIPTION
**Pull request by samderanova**
Resolves #371.

### CODE REVIEW

File: apps/site/src/app/admin/participants/components/ParticipantAction.tsx [hunk 1]
```diff
@@ -55,16 +55,20 @@ function ParticipantAction({
 			variant="inline-link"
 			ariaLabel={`Confirm attendance for ${participant._id}`}
 			onClick={() => initiateConfirm(participant)}
-			disabled={!isCheckin}
+			disabled={nonHacker && isWaiverSigned && role !== "director"}
```
Comment (taesungh) [inline apps/site/src/app/admin/participants/components/ParticipantAction.tsx:58]: Sorry, can you also allow check-in leads to confirm following from #372.

File: apps/site/src/app/admin/participants/components/ParticipantAction.tsx [hunk 2]
```diff
@@ -55,16 +55,19 @@ function ParticipantAction({
 			variant="inline-link"
 			ariaLabel={`Confirm attendance for ${participant._id}`}
 			onClick={() => initiateConfirm(participant)}
-			disabled={!isCheckin}
+			disabled={!isCheckinLead}
```
Comment (taesungh) [inline apps/site/src/app/admin/participants/components/ParticipantAction.tsx:58]: Issue: should be value not function?

**Review by taesungh — APPROVED** [review]
